# Miyabi Configuration
project_name: meta_cognition_ios_scaffold
version: "0.1.0"

# GitHub settings (use environment variables for sensitive data)
# github_token: ${{ GITHUB_TOKEN }}

# Agent settings
agents:
  enabled: true
  use_worktree: true
  worktree_base_path: ".worktrees"

# Logging
logging:
  level: info
  directory: "./logs"

# Reporting
reporting:
  directory: "./reports"
